const actions = {
    CATEGORIES_GET_ALL: 'CATEGORIES_GET_ALL',
    CATEGORIES_REQUEST_GET_ALL: 'CATEGORIES_REQUEST_GET_ALL',
    POSTS_EDIT: 'POSTS_EDIT',
    POSTS_GET_ALL: 'POSTS_GET_ALL',
    POSTS_GET_ALL_BY_CATEGORY: 'POSTS_GET_ALL_BY_CATEGORY',
    POSTS_REMOVE: 'POSTS_REMOVE',
    POSTS_REQUEST_EDIT: 'POSTS_REQUEST_EDIT',
    POSTS_REQUEST_GET_ALL: 'POSTS_REQUEST_GET_ALL',
    POSTS_REQUEST_GET_ALL_BY_CATEGORY: 'POSTS_REQUEST_GET_ALL_BY_CATEGORY',
    POSTS_REQUEST_REMOVE: 'POSTS_REQUEST_REMOVE',
    POSTS_REQUEST_SAVE: 'POSTS_REQUEST_SAVE',
    POSTS_SAVE: 'POSTS_SAVE'
}

export { actions }
