const actions = {
    CATEGORIES_GET_ALL: 'CATEGORIES_GET_ALL',
    CATEGORIES_REQUEST_GET_ALL: 'CATEGORIES_REQUEST_GET_ALL',
    POSTS_GET_ALL: 'POSTS_GET_ALL',
    POSTS_REQUEST_GET_ALL: 'POSTS_REQUEST_GET_ALL',
    POSTS_REQUEST_SAVE: 'POSTS_REQUEST_SAVE',
    POSTS_SAVE: 'POSTS_SAVE'
}

export { actions }
